name: Build Parch ISO

on:
  release:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packages via Pacman
        run: |
          pacman -Syu --noconfirm archiso reflector rsync curl

      - name: Change Arch Docker mirror
        run: |
          reflector --verbose --country 'United States' -l 5 --sort rate --save /etc/pacman.d/mirrorlist

      - name: Build image
        run: |
          mkarchiso -v iso/

      - name: Generate hash
        id: hash
        run: |
          cd out/
          echo "hash=$(sha256sum ./**.iso | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Upload ISO artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/
          asset_name: my-artifact-${{ github.ref }}.iso
          asset_content_type: application/octet-stream
          
